Add basic CLI
lirantal/opn-shell pull request #3
Opened 2019-01-31 21:49 UTC by zacanger

## Description

Adds simple CLI for usage with npx or whatever. I tried to use `npm run commit` but it failed -- It looks like the commitizen config is incorrect.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Closes #2 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] I have updated the documentation (if required).
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

2019-01-31 21:58 UTC, zacanger commented on README.md
> +TerminalLauncher.launchTerminal({ path: executable }).catch(err => {
This bit in the docs was incorrect

2019-02-01 10:25 UTC, lirantal requested changes

2019-02-01 10:25 UTC, lirantal commented on README.md
> +TerminalLauncher.launchTerminal({ path: executable }).catch(err => {
good catch!

2019-02-01 10:25 UTC, lirantal commented on cli.js
> +    throw err
because nothing catches this throw then it will show an unhandled exception, so let's remove that.
small semantics, but if you're at it and want to change `console.log` to `console.error` that would be nice

2019-02-01 10:25 UTC, lirantal commented on cli.js
> +#!/usr/bin/env node
just my own preference about putting `cli.js` into `./bin/cli.js` so it is more obvious than having it in the project root. if you're up for it of course!

2019-02-01 10:25 UTC, lirantal commented
@zacanger thank you this is really good!

2019-02-01 10:27 UTC, lirantal commented
Love the screenshot addition! Is it yours? :)

2019-02-01 16:53 UTC, zacanger commented
No, not my cat, sadly! I think I found it on <https://twitter.com/catsu>!

2019-02-01 19:40 UTC, lirantal commented
awesome job, thanks! 🚀

2019-02-01 19:40 UTC, merged

2019-02-01 19:42 UTC, lirantal commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/opn-shell)
- [GitHub release](https://github.com/lirantal/opn-shell/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: